apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
  namespace: vulcan-komal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      imagePullSecrets:
        - name: acr-secret-komal
      containers:
        - name: spring-petclinic
          image: vulcanacr.azurecr.io/demo-komal:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always

