apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-service
  namespace: vulcan-komal
spec:
  selector:
    app: spring-petclinic
  ports:
    - protocol: TCP
      port: 80         # Service port
      targetPort: 8080 # Container port
  type: LoadBalancer  # Change to ClusterIP or NodePort if needed
