apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: java-ci-pipeline
  namespace: vulcan-komal
spec:
  params:
    - name: git-url
      description: "Git repository URL"
      type: string
    - name: git-revision
      description: "Git branch to build"
      type: string
      default: "main"
    - name: acr-server
      description: "Azure Container Registry server"
      type: string
    - name: image-name
      description: "Name of the container image"
      type: string
    - name: image-tag
      description: "Tag of the container image"
      type: string
      default: "latest"
    - name: image-url
      type: string
      description: "Full URL of the image to push (e.g., myacr.azurecr.io/spring-petclinic:latest)"
  workspaces:
    - name: shared-workspace
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      params:
        - name: url
          value: "$(params.git-url)"
        - name: revision
          value: "$(params.git-revision)"
        - name: deleteExisting
          value: "true"
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: build-app
      runAfter: ["fetch-repository"]
      taskRef:
        name: maven-build
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: build-and-push-image
      runAfter: ["build-app"]
      taskRef:
        name: kaniko-build
      params:
        - name: image-url
          value: $(params.image-url)
        - name: acr-server
          value: "$(params.acr-server)"
        - name: image-name
          value: "$(params.image-name)"
        - name: image-tag
          value: "$(params.image-tag)"
      workspaces:
        - name: source
          workspace: shared-workspace
