apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
  namespace: vulcan-komal
spec:
  workspaces:
    - name: output
  params:
    - name: url
      type: string
    - name: revision
      type: string
    - name: deleteExisting
      type: string
      default: "false"
  steps:
    - name: clone
      image: alpine/git
      script: |
        #!/bin/sh

        set -e
        if [ "$(params.deleteExisting)" = "true" ]; then
          rm -rf /workspace/output && mkdir -p /workspace/output  # ✅ Ensures a fully clean workspace
        fi
        git clone --depth=1 --branch $(params.revision) $(params.url) /workspace/output
        ls -la /workspace/output   # ✅ Debug: Check the cloned files

